spring.application.name=repository
#########################################################################
#                               SWAGGER                                 #
#########################################################################
#server.port=${PORT:0}
server.port=33000
#habilitar  api docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
#definir la ruta de la documentacion
springdoc.swagger-ui.path=/doc/swagger-ui.html
#paquetes y clase a escanear
#springdoc.packages-to-scan=
springdoc.paths-to-match=/text/**, /api/**, /xyz/**
#ruta por defecto
server.servlet.context-path=/service
############################################################
#                         kafka                            #
############################################################
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=repository-service
spring.kafka.producer.retries=1
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
app.kafka.topic.repository-query=REPOSITORY_QUERY
app.kafka.topic.repository-response=REPOSITORY_RESPONSE
############################################################d
#                        MONGO                             #
############################################################
app.mongo.uri=mongodb://alex:alex8080@localhost:27017/listenme?authSource=admin
app.mongo.database=listenme
