spring.profiles.active=${AMBIENTE:local}

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
