spring.application.name=repository
app.kafka.topic.repository-query=REPOSITORY_QUERY
app.kafka.topic.repository-response=REPOSITORY_RESPONSE
app.mongo.uri=mongodb://alex:alex8080@localhost:27017/listenme?authSource=admin
app.mongo.database=listenme
