apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repository
  namespace: default
  labels:
    app: repository
    component: storm-core
spec:
  ingressClassName: nginx
  rules:
    - host: storm-repo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: repository
                port:
                  number: 8080
