apiVersion: v1
kind: Secret
metadata:
  name: repository-secrets
  namespace: storm-staging
type: Opaque
stringData:
  mongo-uri: "mongodb://alex:alex8080@host.minikube.internal:27017/?authSource=admin"
